from flask import Blueprint, request, jsonify
from app.services.firebase_service import FirebaseService
from datetime import datetime

freeze_bp = Blueprint('freeze', __name__)

def verify_and_get_user():
    auth_header = request.headers.get('Authorization', '')
    if not auth_header.startswith('Bearer '):
        return None
    token = auth_header.split(' ')[1]
    decoded = FirebaseService.verify_token(token)
    if not decoded:
        return None
    uid = decoded['uid']
    return FirebaseService.get_document('users', uid)

@freeze_bp.route('/request', methods=['POST'])
def create_freeze_request():
    user = verify_and_get_user()
    if not user or user.get('role') not in ['admin', 'source-bank', 'cybercrime']:
        return jsonify({'error': 'Unauthorized to create freeze requests'}), 403

    data = request.get_json() or {}
    case_id = data.get('caseId')
    account = data.get('account')
    bank = data.get('bank')
    amount = data.get('amount')

    if not case_id or not account or not bank or not amount:
        return jsonify({'error': 'Missing required fields (caseId, account, bank, amount)'}), 400

    req_id = f"FR-{int(datetime.utcnow().timestamp())}"
    request_data = {
        'id': req_id,
        'caseId': case_id,
        'account': account,
        'bank': bank,
        'sourceBank': user.get('org', 'Source Bank'),
        'amount': amount,
        'status': 'Pending',
        'requestedOn': datetime.utcnow().isoformat(),
        'sla': '4.5h left'
    }

    FirebaseService.set_document('freeze_requests', req_id, request_data)

    # Log in timeline
    timeline_node = {
        'caseId': case_id,
        'time': datetime.utcnow().strftime('%Y-%m-%d %H:%M'),
        'title': 'Freeze request issued',
        'desc': f"Immediate hold request issued to {bank} for beneficiary account {account}.",
        'done': True
    }
    FirebaseService.add_document('timelines', timeline_node)

    return jsonify({'message': 'Freeze request generated successfully', 'request': request_data}), 201

@freeze_bp.route('/requests', methods=['GET'])
def list_freeze_requests():
    user = verify_and_get_user()
    if not user:
        return jsonify({'error': 'Unauthorized'}), 401

    role = user.get('role')
    org = user.get('org')

    filters = []
    # Destination Bank sees requests targeted to them
    if role == 'destination-bank':
        filters.append(('bank', '==', org))
    # Source Bank sees requests generated by them
    elif role == 'source-bank':
        filters.append(('sourceBank', '==', org))

    requests_list = FirebaseService.list_documents('freeze_requests', filters)
    return jsonify({'requests': requests_list}), 200

@freeze_bp.route('/requests/<req_id>/approve', methods=['POST'])
def approve_request(req_id):
    user = verify_and_get_user()
    if not user or user.get('role') not in ['admin', 'destination-bank']:
        return jsonify({'error': 'Unauthorized to approve hold requests'}), 403

    req = FirebaseService.get_document('freeze_requests', req_id)
    if not req:
        return jsonify({'error': 'Request not found'}), 404

    req['status'] = 'Approved'
    req['sla'] = 'Met'
    FirebaseService.set_document('freeze_requests', req_id, req)

    # Update case status
    case_id = req.get('caseId')
    case = FirebaseService.get_document('cases', case_id)
    if case:
        case['status'] = 'Funds Frozen'
        FirebaseService.set_document('cases', case_id, case)

    # Add timeline step
    timeline_node = {
        'caseId': case_id,
        'time': datetime.utcnow().strftime('%Y-%m-%d %H:%M'),
        'title': 'Freeze request approved',
        'desc': f"{req['bank']} placed hold on the beneficiary account ending in {req['account'][-4:]}.",
        'done': True
    }
    FirebaseService.add_document('timelines', timeline_node)

    # Log audit
    audit_data = {
        'actor': f"{user.get('name')} (Freeze Officer)",
        'action': f"Approved hold request {req_id} for amount ₹{req['amount']:,}",
        'time': datetime.utcnow().strftime('%Y-%m-%d %H:%M'),
        'ip': request.remote_addr
    }
    FirebaseService.add_document('audit_logs', audit_data)

    return jsonify({'message': 'Freeze request approved', 'request': req}), 200

@freeze_bp.route('/requests/<req_id>/reject', methods=['POST'])
def reject_request(req_id):
    user = verify_and_get_user()
    if not user or user.get('role') not in ['admin', 'destination-bank']:
        return jsonify({'error': 'Unauthorized to reject hold requests'}), 403

    data = request.get_json() or {}
    reason = data.get('reason', 'N/A')

    req = FirebaseService.get_document('freeze_requests', req_id)
    if not req:
        return jsonify({'error': 'Request not found'}), 404

    req['status'] = 'Rejected'
    req['reason'] = reason
    req['sla'] = 'Met'
    FirebaseService.set_document('freeze_requests', req_id, req)

    # Add timeline step
    timeline_node = {
        'caseId': req.get('caseId'),
        'time': datetime.utcnow().strftime('%Y-%m-%d %H:%M'),
        'title': 'Freeze request rejected',
        'desc': f"Hold request rejected by {req['bank']}. Reason: {reason}",
        'done': False
    }
    FirebaseService.add_document('timelines', timeline_node)

    return jsonify({'message': 'Freeze request rejected', 'request': req}), 200
